---
title: "Homework 1"
author: "Name1, Name2 and Name3"
date: '2018-09-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1 (Chapter 2, #1, 8 marks)

(a) <your answer here>

(b) <etc.>

(c)

(d)


## Question 2 (Chapter 2, #2, 6 marks)

(a)
Regression problem.
Inference.
p = 3, n = 500

(b)
Classification.
Prediction.
p = 13, n = 20

(c)
Regression.
Prediction.
p = 3, n = 52
## Question 3 (Chapter 2, #9, 8 marks)

```{r}
library(ISLR) # use install.packages("ISLR") to install
data(Auto)
head(Auto)
```

(a)
mps, cylinders, displacement, horsepower, weight, acceleration are quantative.
origin, name, year are qualitive

(b)
Ranges: 

      mpg cylinders displacement horsepower weight acceleration
[1,]  9.0         3           68         46   1613          8.0
[2,] 46.6         8          455        230   5140         24.8

> 
```{r}
# Hints:
#   with(Auto,range(mpg)); with(Auto,range(cylinders)), etc.
# or you can use apply() on subsets of columns
apply(Auto[,1:5],MARGIN=2,FUN=range)
# or we can name the output of range and call apply
myr <- function(x) {
  out <- range(x)
  names(out) <- c("min","max")
  out
}
apply(Auto[,1:5],MARGIN=2,FUN=myr)
```


(c)

```{r}
# Hint
meansd <- function(x) {
  out<-c(mean(x),sd(x))
  names(out) <- c("mean","SD")
  out
}
```


(d)

```{r}
# Hint:
AutoSubset <- Auto[c(1:9,86:nrow(Auto)),1:7]
```

(e)

(f)